# Figaro: Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

# dotenv.. Copy this file into a new file called ".env" in the root of the project.
# The dotenv gem will load the contents of .env into the environment when
# Rails starts. Access values like this: ENV["SECRET_KEY_BASE"]
#
# The purpose of this file is to keep secrets out of source control.
# For more information, see: https://github.com/bkeepers/dotenv
# gem 'dotenv-rails', '>= 2.0.0'



DATABASE_USERNAME: d
DATABASE_PASSWORD: d
DBPASS1: a
SECRET_KEY_BASE: key

# Intercept mail on staging, to be sent to the following recipients
# Example: "user@domain.tld,other-user@domain.tld"
#STAGING_MAIL_INTERCEPT_EMAIL_RECIPIENTS=

#ERRBIT_PROJECT_KEY=
#ERRBIT_HOST=https://example.host.tld:8080

#Rails.env=Production
#FOO=test23
